apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: calc-namespace
  labels:
    Project: calc
    division: finance
spec:
  replicas: 2
  selector:
    matchLabels:
      Project: calc
      division: finance
  template:
    metadata:
      labels:
        Project: calc
        division: finance
    spec:
      containers:
        - name: frontend
          image: muralielavarthi/frontend:1.0.0
