apiVersion: v1
kind: Service
metadata:
  name: calc-load-balancer-service-frontend
  namespace: calc-namespace
spec:
  type: LoadBalancer
  selector:
    Project: calc
    division: finance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
