apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: calc-namespace
  labels:
    project: calc
    division: finance
spec:
  type: LoadBalancer
  selector:
    project: calc
    division: finance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
