apiVersion: v1
kind: Service
metadata:
  name: calc-cluster-ip-service-backend
  namespace: calc-namespace
  labels:
    project: calc
    division: finance
spec:
  selector:
    project: calc
    division: finance
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
